### PR TITLE
feat: Implement variable integer encoding

### LINKED ISSUE #6: Variable integer encoding

### PR DESCRIPTION
**Pull request by SuperManifolds**
## Description
Changes the encoding of all multi byte integers to use a variable encoding

Fixes #6

## Type of change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
Tests updated

## Linting

Please make sure you've run the following and fixed any issues that arise:

- [x] `cargo fmt --all -- --check` has been run
- [x] `clip` has been run

## Final Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by pojntfx — COMMENTED** [review]
Looks pretty good too me!

One question though: Would it make sense to keep the fixed-size versions? Protobuf has the fixed types, like `fixed64` - currently we just use the non-fixed version, but we could definitely be closer to the spec if we kept the fixed versions for that purpose :)

**Comment by SuperManifolds** [comment]
Thoughts, @ShivanshVij ?

**Comment by SuperManifolds** [comment]
In conversation with Shiv the decision was made to keep as it is now and adopt support for fixed32 and fixed64 in a later version

**Review by ShivanshVij — APPROVED** [review]
LGTM

**Pull request merged**
